# Generated by Django 3.2 on 2023-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230520_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('moderator', 'Moderator'), ('admin', 'Admin'), ("[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')]", 'Role Choices')], default='user', max_length=200, verbose_name='Роль'),
        ),
    ]
