# Generated by Django 3.2 on 2023-05-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': ('Категория:',),
                'verbose_name_plural': 'Категории:',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': ('Жанр:',),
                'verbose_name_plural': 'Жанры:',
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('year', models.PositiveIntegerField()),
                ('desription', models.TextField()),
                ('category', models.ForeignKey(help_text='Выберите категорию:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='rewiews.categories', verbose_name='Категория:')),
                ('genre', models.ManyToManyField(help_text='Выберите жанр:', null=True, related_name='titles', to='rewiews.Genres', verbose_name='Жанр:')),
            ],
            options={
                'verbose_name': ('Произведение:',),
                'verbose_name_plural': 'Произведения:',
            },
        ),
        migrations.CreateModel(
            name='TitlesGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titlesgenres', to='rewiews.titles')),
            ],
        ),
    ]
